# Generated by Django 4.2.6 on 2023-10-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='service',
            new_name='selected_service',
        ),
    ]
